#!/usr/bin/bash                                                                                                                             
                                                                                                                                                
echo " ${cd} "

